### ISSUE TITLE
user : create form registration

### ISSUE THREAD

**Issue by esauvage1978** [esauvage1978/oc_project6#3]
With field : username, email, password

**Comment by Jduret** [comment]
Given I am on the Home page
When I click to the "Register" button
Then I wan't to see a form 
With "Name"
        "Firstname"
        "email"
        "password"
And  "Save" button

**Comment by esauvage1978** [comment]
Scenario: find form
        Given I am on homepage
        When I follow "Sign up"
        Then I should see a "form" element
        And I should see a "Username" element
        And I should see a "Email" element
        And I should see a "Password" element
        And I should see a "Create an account" element

Create Entity -> Create database (Issue 1)
Create Form
